project_name: ctop
builds:
  - id: ctop
    main: main.go
    binary: ctop
    ldflags: -s -w -X main.Version="v{{.Version}}-{{.CommitDate}}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
    goarm:
      - 7

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    strip_parent_binary_folder: true
    files:
      - README.md
      - LICENSE

announce:
  twitter:
    # Wether its enabled or not.
    # Defaults to false.
    enabled: false